[package]
name = "deep"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
dirs = "6.0.0"
rusqlite = { version = "0.38.0", features = ["bundled"] }
thiserror = "2.0.17"
time = { version = "0.3.44", features = ["formatting"] }
